// <auto-generated />
using System;
using MemosWebInfrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MemosWebAPI.Migrations
{
    [DbContext(typeof(MemosBdContext))]
    [Migration("20250909140835_AjoutIndexUniqueCompteNomUtilisateur")]
    partial class AjoutIndexUniqueCompteNomUtilisateur
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("MemosWebAPI.Entites.Compte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime?>("DateDerniereConnexion")
                        .HasColumnType("DATETIME");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NomUtilisateur")
                        .IsUnique();

                    b.ToTable("Compte", (string)null);
                });

            modelBuilder.Entity("MemosWebAPI.Entites.Memo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCompte")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdCompte");

                    b.ToTable("Memo", (string)null);
                });

            modelBuilder.Entity("MemosWebAPI.Entites.Memo", b =>
                {
                    b.HasOne("MemosWebAPI.Entites.Compte", "IdCompteNavigation")
                        .WithMany("Memos")
                        .HasForeignKey("IdCompte")
                        .IsRequired();

                    b.Navigation("IdCompteNavigation");
                });

            modelBuilder.Entity("MemosWebAPI.Entites.Compte", b =>
                {
                    b.Navigation("Memos");
                });
#pragma warning restore 612, 618
        }
    }
}
